[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx", "nodejs_18", "npm-9_x", "libmysqlclient"]

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "composer install --no-dev --optimize-autoloader",
  "npm i"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"